# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c3f451217fe7486109f5691629f1e19e4950e13cca542d024a71841aa0eca2b88654fc45dcfaa4dbefdd430bc13df798fb6aef59b84c93990c804cf735ea5d

test:
  secret_key_base: dfe394961eb6cc208ef6828fc302768ef52eaec501f22dd3691daa8a9aaea39e72465ac2deffdce03843bd68a14eec9dbe1105be313b27e14b2d482e90138a8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
